apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-central
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman-central
  template:
    metadata:
      labels:
        app: pacman-central
    spec:
      volumes:
        - name: kubeconfig-volume
          configMap:
            name: kubeconfig-files
      containers:
        - name: pacman-central
          image: clairegregg/pacman-central:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://admin:password@mongodb:27017"
            - name: KUBECONFIGS
              value: "/etc/kubeconfigs/config1.yaml,/etc/kubeconfigs/config2.yaml,/etc/kubeconfigs/config3.yaml"
            - name: KAFKA_BOOTSTRAP_SERVER
              value: "kafka.clairegregg.com:80"
          volumeMounts:
            - name: kubeconfig-volume
              mountPath: "/etc/kubeconfigs"
              readOnly: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig-files
data:
  config1.yaml: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: ${CHUNK1_CERT_AUTH}
        server: ${CHUNK1_SERVER}
      name: kind-chunk1
    contexts:
    - context:
        cluster: kind-chunk1
        user: kind-chunk1
      name: kind-chunk1
    current-context: kind-chunk1
    kind: Config
    preferences: {}
    users:
    - name: kind-chunk1
      user:
        client-certificate-data: ${CHUNK1_CERT_DATA}
        client-key-data: ${CHUNK1_KEY_DATA}
  config2.yaml: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: ${CHUNK2_CERT_AUTH}
        server: ${CHUNK2_SERVER}
      name: kind-chunk2
    contexts:
    - context:
        cluster: kind-chunk2
        user: kind-chunk2
      name: kind-chunk2
    current-context: kind-chunk2
    kind: Config
    preferences: {}
    users:
    - name: kind-chunk2
      user:
        client-certificate-data: ${CHUNK2_CERT_DATA}
        client-key-data: ${CHUNK2_KEY_DATA}
  config3.yaml: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: ${CHUNK3_CERT_AUTH}
        server: ${CHUNK3_SERVER}
      name: kind-chunk3
    contexts:
    - context:
        cluster: kind-chunk3
        user: kind-chunk3
      name: kind-chunk3
    current-context: kind-chunk3
    kind: Config
    preferences: {}
    users:
    - name: kind-chunk3
      user:
        client-certificate-data: ${CHUNK3_CERT_DATA}
        client-key-data: ${CHUNK3_KEY_DATA}
---
apiVersion: v1
kind: Service
metadata:
  name: pacman-central
spec:
  selector:
    app: pacman-central
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
