version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  central_server:
    build:
      context: ./central_server/src/central_server
      dockerfile: Dockerfile
    container_name: central_server
    ports:
      - "8080:8080"
    # Mount the local source code to /app in the container for host reload
    volumes:
      - ./central_server/src/central_server:/app
    environment:
      # Example environment variable for connecting to Mongo
      - MONGO_URI=mongodb://root:example@mongo:27017/?authSource=admin
    depends_on:
      - mongo
    command: ["go", "run", "main.go"]

  chunk_server_1:
    build:
      context: ./chunk_server/src/chunk_server
      dockerfile: Dockerfile
    container_name: chunk_server_1
    ports:
      - "8081:8080"
    volumes:
      - ./chunk_server/src/chunk_server:/app
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/?authSource=admin
    depends_on:
      - mongo
    command: ["go", "run", "main.go"]

  chunk_server_2:
    build:
      context: ./chunk_server/src/chunk_server
      dockerfile: Dockerfile
    container_name: chunk_server_2
    ports:
      - "8082:8080"
    volumes:
      - ./chunk_server/src/chunk_server:/app
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/?authSource=admin
    depends_on:
      - mongo
    command: ["go", "run", "main.go"]