apiVersion: apps.kruise.io/v1beta1
kind: StatefulSet
metadata:
  name: pacman-chunk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pacman-chunk
  serviceName: "pacman-chunk"  # Each headless service will be accessible as something like pacman-chunk-0.pacman-bhunk
  template:
    metadata:
      labels:
        app: pacman-chunk
    spec:
      containers:
        - name: pacman-chunk
          image: clairegregg/pacman-chunk:latest
          ports:
            - containerPort: 8080