apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: {{ .Values.caddy.replicas }}
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: {{ .Values.caddy.image }}
          ports:
            - containerPort: {{ .Values.caddy.ports.http }}
            - containerPort: {{ .Values.caddy.ports.https }}
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-config
