name: Chunk Server - Docker Image 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with: 
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/pacman-chunk:latest
        context: chunk_server/src/chunk_server
