name: Deploy Chunk Server 3 Update

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Chunk Server - Docker Image']
    branches: ["main"]
    types: [completed]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'chunk'
        namespace: 'default'
        chart: 'chunk_server/helm/chunk/app'
        value-files: 'chunk_server/helm/values'
      env:
        KUBECONFIG_FILE: '${{ secrets.CHUNK_SERVER_3_KUBECONFIG }}'


