name: Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and push Docker images
              uses: docker/build-push-action@v6
              with: 
                tags: ${{ vars.DOCKERHUB_USERNAME }}/pacman-frontend:latest
                context: frontend
    
    deploy:
        runs-on: ubuntu-latest

        steps: 
            - name: Deploy via ssh
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ vars.SERVER_HOST }}
                username: ${{ vars.SERVER_USERNAME }}
                key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
                port: 22
                script: |
                    docker ps -q --filter "name=frontend" | grep -q . && docker stop frontend && docker rm frontend || echo "No running container"
                    docker run -d --name frontend -p 3000:3000 ${{ vars.DOCKERHUB_USERNAME }}/pacman-frontend:latest

