name: Deploy Chunk Server 3 Update

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Chunk Server - Docker Image']
    branches: ["main"]
    types: [completed]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install kubectl
      uses: azure/setup-kubectl@v4
    - name: Configure kubeconfig
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.CHUNK_SERVER_3_KUBECONFIG }}
    - name: Deploy to K8s cluster
      uses: azure/k8s-deploy@v5
      with:
        action: deploy
        manifests: |
          chunk_server/k8s

